# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fec395994195b5c65c3b63a739c80ea546bf84ee33c1e3fc6d65548170d9141b0779bb44cd8151cc898daeeacb37f59edb2f94fa9e3488e3e10627db039b8a3

test:
  secret_key_base: 1dc6f27bdd40b75fb4ae9b4c1dd1342e560d467fe5addc804903048d5fce10d203cdddc4fed130f1de398f85d597acb1d58c05bd2e0177338a387c2e1f4977d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
